version: '3.7'

services:

  app:
    hostname: app
    build: .
    depends_on:
      - db
    ports:
      - 55000:5000
    volumes:
      - .:/home/microblog
    environment:
      FLASK_DEBUG: 1
      DATABASE_URL: mysql+pymysql://app:secret@db:3306/test

  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
    ports:
      - 33306:3306
      - 33307:33060
    volumes:
      - ./data:/var/lib/mysql
